### ISSUE TITLE
Admin tool or API ?

### ISSUE THREAD

**Issue by oktayaa** [afterlogic/webmail-lite-8#13]
MariaDB [afterlogic8]> show tables;
+------------------------------+
| Tables_in_afterlogic8        |
+------------------------------+
| au_eav_attributes_bool       |
| au_eav_attributes_datetime   |
| au_eav_attributes_double     |
| au_eav_attributes_int        |
| au_eav_attributes_mediumblob |
| au_eav_attributes_string     |
| au_eav_attributes_text       |
| au_eav_entities              |
| au_min_hashes                |
+------------------------------+
9 rows in set (0.00 sec)

I see the database schema has changed to the above. Trying to work with it is like trying to edit a binary file with a hex editor. Is there an interface for this anywhere? To see users, their settings etc?

**Comment by afterlogic-support** [comment]
Our team uses EAV Viewer for accessing those data directly. In the latest package, there's a known bug which doesn't allow for using the Viewer. The bug is already fixed in the repository so you can install the product from Github, or just grab the specific module, unpack it and overwrite one in your installation:
https://github.com/afterlogic/aurora-module-eav-object-viewer
Within next few days, we'll be updating the package so the issue will be fixed there.
