### ISSUE TITLE
IMAP - Block domains

### ISSUE THREAD

**Issue by garciacarmonaam** [afterlogic/webmail-lite-8#30]
Hello,

I cannot find any PHP API function to block e-mails from certain domains. Anyway, because of not being the inbox interface such a PHP interface of easy management, it is hard to track where are received e-mails tracked to show.

Regards,
Ángel Manuel.

**Comment by afterlogic-support** [comment]
WebMail Pro doesn't have such a feature, hence that's not doable via API either. But of course, since it's a free open-source product, you're allowed to modify the source code and implement any feature you require. 

Please keep in mind though: WebMail doesn't store emails anywhere and doesn't index them either, thus consider making this kind of adjustments on mail server side, rather than on webmail end.
