### ISSUE TITLE
Display both email address and name in From: to avoid Email Name Spoofing

### ISSUE THREAD

**Issue by oktayaa** [afterlogic/webmail-lite-8#37]
It is becoming very common for the sender name to spoof an existing user's full name while the email is actually coming from a scammer. 

It would be useful if there was an option to display both the name and the email address of the sender in the email list panel to be able to identify these easier.

**Comment by afterlogic-support** [comment]
Please feel free to post a vote at https://afterlogic.uservoice.com/
If the feature gets substantial amount of votes, we'll consider adding it in the future versions.
Alternately, since we're speaking of an opensource product, you can add the feature yourself and create a pull request so the feature is included in WebMail Lite.
