### ISSUE TITLE
My afterlogic webmail lite install page is not working. When i set mydomain/install it showing page not found.

### ISSUE THREAD

**Issue by Aniruddha-f** [afterlogic/webmail-lite-8#53]

**Comment by afterlogic-support** [comment]
There's no such URL in terms of WebMail Lite 8, however there's **?install** key you can add to URL, in order to enter compatibility test. Please see [Compatibility Test](https://afterlogic.com/docs/webmail-lite-8/installation/compatibility-test) and [Installation Instructions](https://afterlogic.com/docs/webmail-lite-8/installation/installation-instructions) documentation pages.
