### ISSUE TITLE
Visual anti-phishing aid

### ISSUE THREAD

**Issue by oktayaa** [afterlogic/webmail-lite-8#58]
I already submitted this issue #37 but I was told to start a change.org campaign for it and get people to support my cause. I think it's both trivial to implement on your side and very very useful for your users. I think you should reconsider.

![phishing](https://user-images.githubusercontent.com/25581961/75556300-015cda00-5a4f-11ea-8a3a-af8825ada966.jpg)

This was accomplished by changing one line in MessagePaneView.html

From:

`<span class="control address" data-bind="text: currentAccountEmail() === fromEmail() ? meSender : from,
`

To:

` <span class="control address" data-bind="text: fromEmail,`

I am sure you can make this configurable and look better.

Best.

**Comment by afterlogic-support** [comment]
We may actually add this in the future - but, what you have on the screenshot is a collapsed view of address pane, which is kept minimal by design. If you expand the pane by clicking that small arrow icon under it, then from that moment forward, all the address information will be displayed for you in full, thus avoiding the issue.

**Comment by oktayaa** [comment]
That is good to know. ( I will still leave it the way it is for my purposes to make sure the users see it )

Thanks.
