### ISSUE TITLE
Sieve via SSL/TLS

### ISSUE THREAD

**Issue by markv9401** [afterlogic/webmail-lite-8#76]
Please add support to configure Sieve to run on SSL/TLS. (STARTTLS option is implemented but I run mine on SSL/TLS straight. I understand this doesn't add much at all but it doesn't make sense not having the ability to set up any way)

**Comment by afterlogic-support** [comment]
Please feel free to post a feature request at:
https://afterlogic.uservoice.com/forums/932335-webmail-pro
If the feature gets substantial amout of votes, we'll consider implementing it.
And since WebMail Lite and Pro share a large portion of code and functionality, including email and Sieve features, it's OK to post that under WebMail Pro section there.
