### ISSUE TITLE
Error to send email

### ISSUE THREAD

**Issue by tebareinyu** [afterlogic/webmail-lite-8#77]
Hello,

I have this error.

(535 Incorrect authentication data)

**Comment by afterlogic-support** [comment]
Hello,
Are you using the same hostname for both IMAP and SMTP? Because it looks like the credentials you use for IMAP server don't work for SMTP.
I'd recommend to check if you get the same error when trying to send mail out using a different email client, Mozilla Thunderbird for example. Make surre SMTP server details there are supplied the same way they're supplied in WebMail.

**Comment by afterlogic-support** [comment]
Thread closed due to inactivity. Feel free to reopen should the issue occur with the latest version.
