### ISSUE TITLE
plain login

### ISSUE THREAD

**Issue by touringo** [afterlogic/webmail-lite-8#93]
Hi, I am evaluating WebMail lite for embedding on a intranet website, I've set Dovecot to accept plain login. 
With another webclient and with Thunderbird too I've been able to logon but no way to make it happen in WebMail lite. 
I suspect there is plain login disabled somewhere: is there a setting to tweak in order to make it work?

**Comment by afterlogic-support** [comment]
Do you get IMAP authentication error in [debug logs](https://afterlogic.com/docs/webmail-lite/troubleshooting/debug-logging-as-main-troubleshooting-measure) of WebMail? If yes, can you share the relevant part of the logs?

**Comment by afterlogic-support** [comment]
Thanks. However, that's not exactly what I asked. Do the logs not contain communication with IMAP server at all? If so, that isn't related to mailserver authentication mode and has something to do with how webmail is configured, there can be various potential reasons - mail server added incorrectly in adminpanel, attempting to log into an account specifying just the username rather than full email address, and so on. One more thing that comes to mind is [CSRF protection](https://afterlogic.com/docs/webmail-lite/security/csrf-protection), you can try turning it off and see if that helps.

**Comment by touringo** [comment]
I've got a couple of rows from dovecot server, if can help:

Nov 30 14:15:11 9mx dovecot: imap-login: Login: user=<macho@tablet.local>, method=PLAIN, rip=10.116.205.84, lip=10.116.204.112, mpid=2842, session=</TGJu7DuMuUKdM1U>
Nov 30 14:15:11 9mx dovecot: imap(macho@tablet.local)<2842></TGJu7DuMuUKdM1U>: Disconnected: Logged out in=89 out=1097 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0

notice: tablet.local is a domain used in my intranet

**Comment by touringo** [comment]
Just for info, here is mailserver configuration screenshot. I hope it's visible, just pasted it.
![immagine](https://user-images.githubusercontent.com/119513097/204838729-dabd805f-1f2d-490a-ac58-be758fbf19dc.png)

**Comment by touringo** [comment]
Hi, you were right: after deleting a recreating mail server I've able to make customer logon.
Thanks.
